### ISSUE TITLE
Sync Vs Async

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#1005]
Check the documentation for the 'Sync Vs Async' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Sync Vs Async page](https://docs.ros.org/en/iron/Tutorials/Sync-Vs-Async.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by siddux** [comment]
Hi, I'd like to test this!

**Comment by Yadunund** [comment]
@siddux any update?

**Comment by siddux** [comment]
Sorry for the late response, I've performed all the tests without any errors and the documentation is clear. The results, depending if the service is running or not are the following:

![results](https://github.com/osrf/ros2_test_cases/assets/7074956/4bab2733-2876-4c12-b83d-069f555db219)

![result2](https://github.com/osrf/ros2_test_cases/assets/7074956/ec5156d4-c032-4652-85c3-f729fb8ef2cf)

**Comment by clalancette** [comment]
Thank you for testing!
