### ISSUE TITLE
Testing Main

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#1006]
Check the documentation for the 'Testing Main' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Testing Main page](https://docs.ros.org/en/iron/Tutorials/Intermediate/Testing/Testing-Main.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by BorisBoutillier** [comment]
On a debian jammy installation with fastDDS.

I have checked the 4 documentation pages regarding Testing (Main, Running, Writing in Python, Writing in C++).
I have been able to follow the documentation, it was clear to me, and I have not seen any obvious error.
I have been able to create/compile and run tests in both Python and C++.

**Comment by clalancette** [comment]
Thanks for testing!
