### ISSUE TITLE
Topic Statistics Tutorial

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#1011]
Check the documentation for the 'Topic Statistics Tutorial' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Topic Statistics Tutorial page](https://docs.ros.org/en/iron/Tutorials/Advanced/Topic-Statistics-Tutorial/Topic-Statistics-Tutorial.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by SrijaneeBiswas** [comment]
Assigned to myself.

Can confirm all 3 checks:

[x]: I was able to follow the documentation.
[x]: The documentation seemed clear to me.
[x]: The documentation didn't have any obvious errors.

![topic_statistics_issue](https://user-images.githubusercontent.com/30804865/236617625-c2bf956c-67f5-4610-9006-ad17eb97104f.png)

**Comment by clalancette** [comment]
Thank you for testing!
