### ISSUE TITLE
Using Stamped Datatypes With Tf2 Ros MessageFilter

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#1022]
Check the documentation for the 'Using Stamped Datatypes With Tf2 Ros MessageFilter' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Using Stamped Datatypes With Tf2 Ros MessageFilter page](https://docs.ros.org/en/iron/Tutorials/Intermediate/Tf2/Using-Stamped-Datatypes-With-Tf2-Ros-MessageFilter.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by BorisBoutillier** [comment]
On a debian jammy installation with fastDDS.

I have done the "Using Stamped Datatypes with Tf2 Ros MessageFilter" tutorial.
I was able to follow the documentation, it was clear to me , and I did not see any error in wording/code or hyperlinks.

![image](https://user-images.githubusercontent.com/18518188/237062610-89d67e5b-d166-4884-9a69-0eb06b63b124.png)

**Comment by Yadunund** [comment]
Thanks for testing!
