### ISSUE TITLE
Install options in doc are inconsistently named

### ISSUE THREAD

**Issue by cdhabecker** [osrf/ros2_test_cases#1046]
https://docs.ros.org/en/iron/Installation.html

[Problem]
- "Debian" and "RPM" are imprecise terms: the packages are usually binary, but they could be source, too. 
- "fat" archive: this user does not find the word "fat" to add any clarity -- instead, I'm wondering why I haven't been using this term. File Access Table? Now I'm confused.
- The main page describes two types (binary and source), but then the Debian and RPM pages drop "binary" from their type.

[Solution]
- Adopt these names:
- Ubuntu (Debian binary), Ubuntu (archive binary), Ubuntu (source)
- RHEL (RPM binary), RHEL (archive binary), RHEL (source)
- Windows (archive binary), Windows (source)
- macOS (source)

**Comment by Yadunund** [comment]
Hi @cdhabecker,

Thanks for raising this point. Let's continue this discussion here https://github.com/osrf/ros2_test_cases/discussions/1047

Will close this ticket to not mix up discussions and test cases
