### ISSUE TITLE
[jazzy] Add test cases for logging service

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#1059]
Ref: https://github.com/ros2/demos/pull/611

**Comment by marcoag** [comment]
Isn't this covered by: https://docs.ros.org/en/jazzy/Tutorials/Demos/Logging-and-logger-configuration.html#logger-level-configuration-externally ? Or do we wanna add something else?

**Comment by Yadunund** [comment]
I think this ticket was opened before the docs website was updated. So we can close this ticket since a test case for this feature should be generated when scraping the docs sitemap.
