### ISSUE TITLE
RHEL Development Setup

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1066]
Check the documentation for the 'RHEL Development Setup' page

## Configuration

* Chip set: AMD64
* Build type: Source
* OS: RHEL-9
* DDS: FastDDS

## Links

* [RHEL Development Setup page](https://docs.ros.org/en/jazzy/Installation/Alternatives/RHEL-Development-Setup.html)

**Comment by mikaelarguedas** [comment]
Wrongfully labeled "Ubuntu Noble 24.04" ?

**Comment by clalancette** [comment]
> Wrongfully labeled "Ubuntu Noble 24.04" ?

Yeah, good point.  Will fix up the tags.

**Comment by clalancette** [comment]
Step 1 - I was able to follow the documentation.  - Yep!
Step 2 - The documentation seemed clear to me.  - Yep!
Step 3 - The documentation didn't have any obvious errors. - Yep!
