### ISSUE TITLE
RHEL Install Binary

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1067]
Check the documentation for the 'RHEL Install Binary' page

## Configuration

* Chip set: AMD64
* Build type: Binary
* OS: RHEL-9
* DDS: FastDDS

## Links

* [RHEL Install Binary page](https://docs.ros.org/en/jazzy/Installation/Alternatives/RHEL-Install-Binary.html)

**Comment by mikaelarguedas** [comment]
Wrongfully labeled "Ubuntu Noble 24.04" ?

**Comment by clalancette** [comment]
> Wrongfully labeled "Ubuntu Noble 24.04" ?

Yes, will fix this one up.

**Comment by clalancette** [comment]
Step 1 - I was able to follow the documentation. - Yep!
Step 2 - The documentation seemed clear to me. - Yep!
Step 3 - The documentation didn't have any obvious errors. - There were a couple of errors related to rosdep; see https://github.com/ros2/ros2_documentation/pull/4451 for the fixes.

Given that we have the documentation PR open, going ahead and closing this one.
