### ISSUE TITLE
Ubuntu Development Setup

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1068]
Check the documentation for the 'Ubuntu Development Setup' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Ubuntu Development Setup page](https://docs.ros.org/en/jazzy/Installation/Alternatives/Ubuntu-Development-Setup.html)

**Comment by fujitatomoya** [comment]
@marcoag i can check this one too.

**Comment by fujitatomoya** [comment]
@marcoag i think this test case is included within https://github.com/osrf/ros2_test_cases/issues/1065, so we already confirmed this.
