### ISSUE TITLE
Ubuntu Install Binary

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1069]
Check the documentation for the 'Ubuntu Install Binary' page

## Configuration

* Chip set: AMD64
* Build type: Binary
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Ubuntu Install Binary page](https://docs.ros.org/en/jazzy/Installation/Alternatives/Ubuntu-Install-Binary.html)

**Comment by mikaelarguedas** [comment]
Wrongfully labeled as "Build type: Debian"

**Comment by marcoag** [comment]
> Wrongfully labeled as "Build type: Debian"

Updated, thanks!

**Comment by clalancette** [comment]
I'm going to reopen this, as I don't think we had explicit confirmation that things were tested here.

**Comment by mikaelarguedas** [comment]
Indeed I didn't test it :+1:

**Comment by mikaelarguedas** [comment]
Is this different from https://github.com/osrf/ros2_test_cases/issues/1481 ?

If not I believe this can be closed (I tested it for all 3 RMW implementation and submitted some fixups here https://github.com/ros2/ros2_documentation/pull/4369)

**Comment by marcoag** [comment]
Yup, I believe this is a duplicate but of https://github.com/osrf/ros2_test_cases/issues/1480 (FastDDS), will proceed to close again.

@clalancette feel free to reopen if there's something we missed here.
