### ISSUE TITLE
Windows Development Setup

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1070]
Check the documentation for the 'Windows Development Setup' page

## Configuration

* Chip set: AMD64
* Build type: Source
* OS: Windows 10
* DDS: FastDDS

## Links

* [Windows Development Setup page](https://docs.ros.org/en/jazzy/Installation/Alternatives/Windows-Development-Setup.html)

**Comment by mikaelarguedas** [comment]
Wrongfully labeled "Ubuntu Noble 24.04"

**Comment by marcoag** [comment]
> Wrongfully labeled "Ubuntu Noble 24.04"

True, changed that, thanks!
