### ISSUE TITLE
Working with GurumNetworks GurumDDS

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1076]
Check the documentation for the 'Working with GurumNetworks GurumDDS' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Working with GurumNetworks GurumDDS page](https://docs.ros.org/en/jazzy/Installation/DDS-Implementations/Working-with-GurumNetworks-GurumDDS.html)

**Comment by clalancette** [comment]
Closing this one as we don't have GurumDDS working with Jazzy.
