### ISSUE TITLE
Maintaining a Source Checkout

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1078]
Check the documentation for the 'Maintaining a Source Checkout' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Maintaining a Source Checkout page](https://docs.ros.org/en/jazzy/Installation/Maintaining-a-Source-Checkout.html)

**Comment by fujitatomoya** [comment]
@marcoag i can check this, sign me up.

**Comment by fujitatomoya** [comment]
No problem found, i think we can close this.
