### ISSUE TITLE
Ubuntu Install Debians

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1081]
Check the documentation for the 'Ubuntu Install Debians' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Ubuntu Install Debians page](https://docs.ros.org/en/jazzy/Installation/Ubuntu-Install-Debians.html)

**Comment by fujitatomoya** [comment]
@marcoag you can sign me up.

i already verified this one, no problem observed. we can close this.
