### ISSUE TITLE
Advanced Tutorials

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1083]
Check the documentation for the 'Advanced Tutorials' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Advanced page](https://docs.ros.org/en/jazzy/Tutorials/Advanced.html)

**Comment by clalancette** [comment]
This is a top-level page, so I just checked that all links work.  They do indeed, so closing this out.
