### ISSUE TITLE
Allocator Template Tutorial

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1084]
Check the documentation for the 'Allocator Template Tutorial' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Allocator Template Tutorial page](https://docs.ros.org/en/jazzy/Tutorials/Advanced/Allocator-Template-Tutorial.html)

**Comment by clalancette** [comment]
> ### Step 1 - I was able to follow the documentation.

Yep!

> ### Step 2 - The documentation seemed clear to me.

Yep!

> ### Step 3 - The documentation didn't have any obvious errors.

Yep!
