### ISSUE TITLE
FastDDS Configuration

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1086]
Check the documentation for the 'FastDDS Configuration' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [FastDDS Configuration page](https://docs.ros.org/en/jazzy/Tutorials/Advanced/FastDDS-Configuration.html)

**Comment by samuel-ongzx** [comment]
## Process
- [x] Step 1 - I was able to follow the documentation.
- [x] Step 2 - The documentation seemed clear to me.
- [x] Step 3 - The documentation didn't have any obvious errors.

## Testing
Entire [page](https://docs.ros.org/en/jazzy/Tutorials/Advanced/FastDDS-Configuration.html#configuring-a-service-and-a-client) was tested.
- [x] Mixing synchronous and asynchronous publications in the same node (`ok` - setup, env setup, running, verification of output)
- [x] Using other FastDDS capabilities with XML (`ok` - limit subscribers, partitions, verification of output)
- [x] Configuring a service and a client (`ok` - ping service & client, verification of output)

## Verification:
Tested `ok` - async & sync pub
<img width="1722" alt="image" src="https://github.com/osrf/ros2_test_cases/assets/16714436/87019244-4497-453f-a791-62a3ed91f93b">
Tested `ok` - ping
<img width="704" alt="image" src="https://github.com/osrf/ros2_test_cases/assets/16714436/835024ac-74a4-410a-9866-26ccdb016b85">

**Comment by clalancette** [comment]
Fantastic, thank you for testing!
