### ISSUE TITLE
Reading From A Bag File CPP

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1089]
Check the documentation for the 'Reading From A Bag File CPP' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Reading From A Bag File CPP page](https://docs.ros.org/en/jazzy/Tutorials/Advanced/Reading-From-A-Bag-File-CPP.html)

**Comment by clalancette** [comment]
> ### Step 1 - I was able to follow the documentation.

Yep!

> ### Step 2 - The documentation seemed clear to me.

Yep!

> ### Step 3 - The documentation didn't have any obvious errors.

Yep!
