### ISSUE TITLE
Gazebo

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1098]
Check the documentation for the 'Gazebo' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Gazebo page](https://docs.ros.org/en/jazzy/Tutorials/Advanced/Simulators/Gazebo/Gazebo.html)

**Comment by ahcorde** [comment]
See comment here https://github.com/ros2/ros2_documentation/pull/4362#pullrequestreview-2040259763

**Comment by clalancette** [comment]
Closing this one as completed.
