### ISSUE TITLE
Simulation Gazebo

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1099]
Check the documentation for the 'Simulation Gazebo' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Simulation Gazebo page](https://docs.ros.org/en/jazzy/Tutorials/Advanced/Simulators/Gazebo/Simulation-Gazebo.html)

**Comment by jasmeet0915** [comment]
Followed the instructions on the page and was able to get `gz sim` up and running!

![Screenshot from 2024-05-10 02-20-30](https://github.com/osrf/ros2_test_cases/assets/23265149/e44c01f6-6a2f-4140-82b4-3d9ff6caf9f7)

**Comment by ahcorde** [comment]
thank you!
