### ISSUE TITLE
Simulation Main

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1100]
Check the documentation for the 'Simulation Main' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Simulation Main page](https://docs.ros.org/en/jazzy/Tutorials/Advanced/Simulators/Simulation-Main.html)

**Comment by jasmeet0915** [comment]
All the links in the page work correctly!
