### ISSUE TITLE
Installation Windows

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1103]
Check the documentation for the 'Installation Windows' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Installation Windows page](https://docs.ros.org/en/jazzy/Tutorials/Advanced/Simulators/Webots/Installation-Windows.html)

**Comment by Ryanf55** [comment]
I don't think this combo makes sense. You can't follow the windows instructions on Ubuntu.

**Comment by clalancette** [comment]
> I don't think this combo makes sense. You can't follow the windows instructions on Ubuntu.

Yep, good point.  Closing this one.
