### ISSUE TITLE
Beginner CLI Tools

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1110]
Check the documentation for the 'Beginner CLI Tools' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Beginner CLI Tools page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools.html)

**Comment by jasmeet0915** [comment]
All the links work correctly on the page!

**Comment by clalancette** [comment]
Thanks for testing!
