### ISSUE TITLE
Introducing Turtlesim

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1112]
Check the documentation for the 'Introducing Turtlesim' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Introducing Turtlesim page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.html)

**Comment by ganatrask** [comment]
I tried this

I was able to follow the documentation.
The documentation seemed clear to me and didn't had any obvious error 

![Screenshot from 2024-05-02 00-41-30](https://github.com/osrf/ros2_test_cases/assets/28732490/39ec9081-e050-4f89-b3ec-06ecc0744e60)


Can you assign this to me and close this issue?

Thanks.

**Comment by marcoag** [comment]
Great, thanks for testing!
