### ISSUE TITLE
Launching Multiple Nodes

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1113]
Check the documentation for the 'Launching Multiple Nodes' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Launching Multiple Nodes page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools/Launching-Multiple-Nodes/Launching-Multiple-Nodes.html)

**Comment by ganatrask** [comment]
I tried this

I was able to follow the documentation.
The documentation seemed clear to me and didn't had any obvious error 

![Screenshot from 2024-05-02 00-36-31](https://github.com/osrf/ros2_test_cases/assets/28732490/aabd4907-1de0-4dde-8748-887f07c9177d)


Can you assign this to me and close this issue?

Thanks.
