### ISSUE TITLE
Understanding ROS 2 Actions

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1115]
Check the documentation for the 'Understanding ROS 2 Actions' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Understanding ROS2 Actions page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Actions/Understanding-ROS2-Actions.html)

**Comment by ganatrask** [comment]
I tried this

I was able to follow the documentation.
The documentation seemed clear to me and didn't had any obvious error 

![Screenshot from 2024-05-02 00-24-46](https://github.com/osrf/ros2_test_cases/assets/28732490/dd9943d4-4e46-4b49-806d-acc4b9d975b6)

![Screenshot from 2024-05-02 00-24-51](https://github.com/osrf/ros2_test_cases/assets/28732490/5440bf43-0e78-496f-93ce-9dd9864214f2)


Can you assign this to me and close this issue?

Thanks.

**Comment by marcoag** [comment]
Thanks for testing!
