### ISSUE TITLE
Understanding ROS 2 Nodes

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1116]
Check the documentation for the 'Understanding ROS 2 Nodes' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Understanding ROS2 Nodes page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Nodes/Understanding-ROS2-Nodes.html)

**Comment by ganatrask** [comment]
I tried this

I was able to follow the documentation.
The documentation seemed clear to me and didn't had any obvious error 

![Screenshot from 2024-05-02 00-11-29](https://github.com/osrf/ros2_test_cases/assets/28732490/cb6daf56-cbfa-435e-af4e-a47173a3f028)

![Screenshot from 2024-05-02 00-11-55](https://github.com/osrf/ros2_test_cases/assets/28732490/efca190c-a24e-4f79-b232-d0aae087cb20)


Can you assign this to me and close this issue?

Thanks.

**Comment by marcoag** [comment]
Nice! Thanks for the testing.
