### ISSUE TITLE
Understanding ROS 2 Topics

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1119]
Check the documentation for the 'Understanding ROS 2 Topics' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Understanding ROS2 Topics page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.html)

**Comment by ganatrask** [comment]
I tried this

I was able to follow the documentation.
The documentation seemed clear to me and didn't had any obvious error 

![Screenshot from 2024-05-01 22-48-56](https://github.com/osrf/ros2_test_cases/assets/28732490/d864e0c1-807e-4aba-b37d-70c5dce090a3)
![Screenshot from 2024-05-01 22-52-28](https://github.com/osrf/ros2_test_cases/assets/28732490/1fec5da8-c72c-47fb-83e0-0e0c939cbcd1)


Can you assign this to me and close this issue?

Thanks

**Comment by wjwwood** [comment]
Thanks!
