### ISSUE TITLE
Using Rqt Console

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1120]
Check the documentation for the 'Using Rqt Console' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Using Rqt Console page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools/Using-Rqt-Console/Using-Rqt-Console.html)

**Comment by ganatrask** [comment]
I tried this

I was able to follow the documentation.
The documentation seemed clear to me and didn't had any obvious error 

![Screenshot from 2024-05-01 22-39-20](https://github.com/osrf/ros2_test_cases/assets/28732490/75563b03-d236-494f-a09d-4fef51cc19e1)


Can you assign this to me and close this issue?

Thanks.
