### ISSUE TITLE
Beginner Client Libraries

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1121]
Check the documentation for the 'Beginner Client Libraries' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Beginner Client Libraries page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-Client-Libraries.html)

**Comment by clalancette** [comment]
This is just an overview page.  I confirmed that all of the links were valid, so closing this out.
