### ISSUE TITLE
Custom ROS 2 Interfaces

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1125]
Check the documentation for the 'Custom ROS 2 Interfaces' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Custom ROS2 Interfaces page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-Client-Libraries/Custom-ROS2-Interfaces.html)

**Comment by Benjamin-Tan** [comment]
Able to follow the documentation, it is very clear, and no obvious errors. Every step and output is as expected.

**Comment by clalancette** [comment]
Thanks for testing!
