### ISSUE TITLE
Single Package Define And Use Interface

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1128]
Check the documentation for the 'Single Package Define And Use Interface' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Single Package Define And Use Interface page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-Client-Libraries/Single-Package-Define-And-Use-Interface.html)

**Comment by Benjamin-Tan** [comment]
Able to follow the documentation, it is very clear, and no obvious errors. Every step and output is as expected. The extras are very useful

**Comment by clalancette** [comment]
Thanks for testing!
