### ISSUE TITLE
Writing A Simple Cpp Publisher And Subscriber

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1131]
Check the documentation for the 'Writing A Simple Cpp Publisher And Subscriber' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Writing A Simple Cpp Publisher And Subscriber page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Publisher-And-Subscriber.html)

**Comment by slowrunner** [comment]
For config:
- Chip set: AMD64
- Build type: Debian
- OS: Ubuntu Noble 24.04
- DDS: FastDDS

I followed the ["Writing A Simple C++ Pub/Sub" Tutorial"](https://docs.ros.org/en/jazzy/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Publisher-And-Subscriber.html)

1) I was able to follow the doc - no problems
2) The doc was very clear to me - (with my NOOB hat on...)
3) The documentation had no errors that I could detect

And BTW, Ctrl-C generates a very "non-threatening" single line exit - Why do I keep writing ROS in Python?

```
$ ros2 run cpp_pubsub talker
[INFO] [1714925431.817250714] [minimal_publisher]: Publishing: 'Hello, world! 0'
[INFO] [1714925432.317285088] [minimal_publisher]: Publishing: 'Hello, world! 1'
...
^C[INFO] [1714925457.426844144] [rclcpp]: signal_handler(signum=2)
```
and the listener:
```
$ ros2 run cpp_pubsub listener 
[INFO] [1714925451.818238558] [minimal_subscriber]: I heard: 'Hello, world! 40'
[INFO] [1714925452.317571273] [minimal_subscriber]: I heard: 'Hello, world! 41'
...
[INFO] [1714925454.817728934] [minimal_subscriber]: I heard: 'Hello, world! 46'
^C[INFO] [1714925454.969396740] [rclcpp]: signal_handler(signum=2)
```
