### ISSUE TITLE
Writing A Simple Cpp Service And Client

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1132]
Check the documentation for the 'Writing A Simple Cpp Service And Client' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Writing A Simple Cpp Service And Client page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Service-And-Client.html)

**Comment by slowrunner** [comment]
For the ["Writing A Simple C++ Service And Client"](https://docs.ros.org/en/jazzy/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Service-And-Client.html) tutorial: 

with Configuration:
- Chip set: AMD64
- Build type: Debian
- OS: Ubuntu Noble 24.04
- DDS: FastDDS

1) I was able to follow the doc - no problem
2) The instructions were clear what to do, where
3) No errors detected in document/code

```
$ ros2 run cpp_srvcli server
[INFO] [1714937531.008149734] [rclcpp]: Ready to add two ints.
[INFO] [1714937537.645574708] [rclcpp]: Incoming request
a: 2 b: 3
[INFO] [1714937537.645599699] [rclcpp]: sending back response: [5]
^C[INFO] [1714937560.212842828] [rclcpp]: signal_handler(signum=2)


$ ros2 run cpp_srvcli client 2 3
[INFO] [1714937537.646216761] [rclcpp]: Sum: 5

```
