### ISSUE TITLE
Writing A Simple Py Service And Client

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1134]
Check the documentation for the 'Writing A Simple Py Service And Client' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Writing A Simple Py Service And Client page](https://docs.ros.org/en/jazzy/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Py-Service-And-Client.html)

**Comment by slowrunner** [comment]
I followed the [Jazzy "Writing A Simple Py Service and Client" Tutorial](https://docs.ros.org/en/jazzy/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Py-Service-And-Client.html)

- No issue following the doc
- Doc was very clear
- No errors that I could detect
- Result executed with no issue:
```
$ ros2 run py_srvcli service
$ ros2 run py_srvcli client 2 3
[INFO] [1714921688.586855272] [minimal_client_async]: Result of add_two_ints: for 2 + 3 = 5

Service Output:
[INFO] [1714921688.572047391] [minimal_service]: Incoming request
a: 2 b: 3
```
