### ISSUE TITLE
Demos

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1135]
Check the documentation for the 'Demos' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Demos page](https://docs.ros.org/en/jazzy/Tutorials/Demos.html)

**Comment by clalancette** [comment]
This is a overview page.  I verified that all of the links work, so closing.
