### ISSUE TITLE
Quality of Service

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1140]
Check the documentation for the 'Quality of Service' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Quality of Service page](https://docs.ros.org/en/jazzy/Tutorials/Demos/Quality-of-Service.html)

**Comment by fujitatomoya** [comment]
@marcoag i can take this.

**Comment by fujitatomoya** [comment]
@marcoag @clalancette @ahcorde 

most of the procedure worked without any problems.

but i would like to fix a couple of minor things with https://github.com/ros2/ros2_documentation/pull/4438.

**Comment by ahcorde** [comment]
Thank you @fujitatomoya
