### ISSUE TITLE
Service Introspection

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1142]
Check the documentation for the 'Service Introspection' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Service Introspection page](https://docs.ros.org/en/jazzy/Tutorials/Demos/Service-Introspection.html)

**Comment by Benjamin-Tan** [comment]
Tested and working as per the documentation. It was easy to follow.
![Screenshot from 2024-05-05 00-29-34](https://github.com/osrf/ros2_test_cases/assets/25479215/5f23c902-4ffa-4584-9181-5bc3bb48170f)
