### ISSUE TITLE
Intermediate Tutorials

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1144]
Check the documentation for the 'Intermediate Tutorials' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Intermediate page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate.html)

**Comment by jasmeet0915** [comment]
All the links work correctly in the page!
