### ISSUE TITLE
Launch Main

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1148]
Check the documentation for the 'Launch Main' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Launch Main page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Launch/Launch-Main.html)

**Comment by jasmeet0915** [comment]
This is an index page. I have tested all the links and they work correctly!
