### ISSUE TITLE
RViz Main

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1156]
Check the documentation for the 'RViz Main' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [RViz Main page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/RViz/RViz-Main.html)

**Comment by jasmeet0915** [comment]
This is an index page. Both the links work correctly on the page!

**Comment by clalancette** [comment]
Fantastic, thanks for testing!
