### ISSUE TITLE
RViz User Guide

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1157]
Check the documentation for the 'RViz User Guide' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [RViz User Guide page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/RViz/RViz-User-Guide/RViz-User-Guide.html)

**Comment by fujitatomoya** [comment]
@marcoag i can check this.

**Comment by fujitatomoya** [comment]
test result,

![image](https://github.com/osrf/ros2_test_cases/assets/43395114/d28c0d00-c8ce-4d19-b563-acb238e8ff11)

everything works okay including shortcut keys.
