### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1159]
Check the documentation for the 'CLI' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [CLI page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Testing/CLI.html)

**Comment by jasmeet0915** [comment]
I have tested all the commands mentioned in the tutorial with a demo package and they work as expected! All the links seem to be working as well

![Screenshot from 2024-05-09 02-15-20](https://github.com/osrf/ros2_test_cases/assets/23265149/cae0ef9b-1415-4289-8fba-faab1dc03ec8)

**Comment by clalancette** [comment]
Thank you for testing!
