### ISSUE TITLE
Writing basic tests with C++ with gtest

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1160]
Check the documentation for the 'Writing basic tests with C++ with gtest' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Cpp page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Testing/Cpp.html)

**Comment by fujitatomoya** [comment]
@marcoag i can take care of this.

**Comment by fujitatomoya** [comment]
test result,

```shell
CMake Error at /opt/ros/jazzy/share/ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake:77 (message):
  ament_target_dependencies() the passed package name 'std_msgs' was not
  found before
Call Stack (most recent call first):
  CMakeLists.txt:34 (ament_target_dependencies)
```

tutorial does not work. i will try to take a look.

**Comment by fujitatomoya** [comment]
@marcoag https://github.com/ros2/ros2_documentation/pull/4412 can close this issue.
