### ISSUE TITLE
Writing Basic Tests with Python

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1161]
Check the documentation for the 'Writing Basic Tests with Python' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Python page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Testing/Python.html)

**Comment by jasmeet0915** [comment]
I have tested all the instructions in the tutorial with a demo ament_python package and everything works as expected! I just noted a minor typo for which I have opened up a [PR](https://github.com/ros2/ros2_documentation/pull/4408)

![Screenshot from 2024-05-09 02-18-50](https://github.com/osrf/ros2_test_cases/assets/23265149/89a1467c-8cc9-4481-abd1-701ba46e1b71)

**Comment by clalancette** [comment]
Thanks for testing!
