### ISSUE TITLE
Adding A Frame Py

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1164]
Check the documentation for the 'Adding A Frame Py' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Adding A Frame Py page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Adding-A-Frame-Py.html)

**Comment by mikaelarguedas** [comment]
Tutorial clear and completed successfully.

minor fixups at https://github.com/ros2/ros2_documentation/pull/4360

**Comment by marcoag** [comment]
Thanks!
