### ISSUE TITLE
Learning About Tf2 And Time Cpp

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1167]
Check the documentation for the 'Learning About Tf2 And Time Cpp' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Learning About Tf2 And Time Cpp page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Learning-About-Tf2-And-Time-Cpp.html)

**Comment by knmcguire** [comment]
currently following this tutorial so you can assign it to me

**Comment by knmcguire** [comment]
Step 1 2 3 were all good ✅ 

Final result looked like this. I

![image](https://github.com/osrf/ros2_test_cases/assets/11061260/db818230-5253-4e99-8567-d1ae1e590a43)

**Comment by clalancette** [comment]
Thanks for testing!
