### ISSUE TITLE
Tf2 Main

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1170]
Check the documentation for the 'Tf2 Main' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Tf2 Main page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Tf2-Main.html)

**Comment by jasmeet0915** [comment]
This is an index page. I have tested all the links and they work correctly!

**Comment by clalancette** [comment]
Great, thanks for testing!
