### ISSUE TITLE
Time Travel With Tf2 Cpp

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1171]
Check the documentation for the 'Time Travel With Tf2 Cpp' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Time Travel With Tf2 Cpp page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Time-Travel-With-Tf2-Cpp.html)

**Comment by knmcguire** [comment]
You can assign me to this as I'm now following this tutorial

**Comment by knmcguire** [comment]
Step 1,2,3 all seems OK ✅ 

Result of first part of tutorial
![image](https://github.com/osrf/ros2_test_cases/assets/11061260/273b8382-7f6f-4113-ac6e-9bb512aa9f00)

Result of second part of tutorial
![image](https://github.com/osrf/ros2_test_cases/assets/11061260/49528ac1-79cd-4199-95f7-cdf8836749e4)

Just some thought for improvement, I had to read 3 times this part of the tutorial and understand the implications:
```

In our code we asked tf2 the following question: “What was the pose of carrot1 5 seconds ago, relative to turtle2 5 seconds ago?”. This means we are controlling the second turtle based on where it was 5 seconds ago as well as where the first carrot was 5 seconds ago.

However, what we really want to ask is: “What was the pose of carrot1 5 seconds ago, relative to the current position of the turtle2?”.
```

Perhaps something visual could have helped here. But its nitpicking mostly. you can close this issue.

**Comment by marcoag** [comment]
Sounds great, thanks a lot for the testing! closing.

PS: Feel free to open a PR with your suggestion.
