### ISSUE TITLE
Time Travel With Tf2 Py

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1172]
Check the documentation for the 'Time Travel With Tf2 Py' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Time Travel With Tf2 Py page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Time-Travel-With-Tf2-Py.html)

**Comment by fujitatomoya** [comment]
@marcoag referenced URL does not exist, https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Time-Travel-With-Tf2-Py.html

**Comment by ahcorde** [comment]
we removed some tutorials https://github.com/ros2/ros2_documentation/pull/4384 because they never worked
