### ISSUE TITLE
Writing A Tf2 Broadcaster Cpp

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1174]
Check the documentation for the 'Writing A Tf2 Broadcaster Cpp' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Writing A Tf2 Broadcaster Cpp page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Broadcaster-Cpp.html)

**Comment by ottojo** [comment]
i'm testing and reviewing this tutorial, please assign me!

**Comment by ottojo** [comment]
## Setup
`ros:jazzy` docker image

```
   PLATFORM INFORMATION
system           : Linux
platform info    : Linux-6.8.8-1-MANJARO-x86_64-with-glibc2.39
release          : 6.8.8-1-MANJARO
processor        : x86_64

   RMW MIDDLEWARE
middleware name    : rmw_fastrtps_cpp

   ROS 2 INFORMATION
distribution name      : jazzy
distribution type      : ros2
distribution status    : pre-release
release platforms      : {'debian': ['bookworm'], 'rhel': ['9'], 'ubuntu': ['noble']}
```

## Notes

* `turtle_tf2_broadcaster.cpp` is available and builds
* provided launchfile works
* explanation for node and launchfile is clear
* running turtlesim works, resulting TF output is as expected

**Comment by clalancette** [comment]
Thank you for testing!
