### ISSUE TITLE
Writing A Tf2 Listener Py

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1177]
Check the documentation for the 'Writing A Tf2 Listener Py' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Writing A Tf2 Listener Py page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Listener-Py.html)

**Comment by mikaelarguedas** [comment]
Tutorial clear and completed successfully.

minor fixups at https://github.com/ros2/ros2_documentation/pull/4360

**Comment by marcoag** [comment]
Closing and following up on the issue. thanks!
