### ISSUE TITLE
Writing A Tf2 Static Broadcaster Py

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1179]
Check the documentation for the 'Writing A Tf2 Static Broadcaster Py' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Writing A Tf2 Static Broadcaster Py page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Py.html)

**Comment by mikaelarguedas** [comment]
Tutorial clear and completed successfully.

minor fixups at https://github.com/ros2/ros2_documentation/pull/4360

**Comment by mikaelarguedas** [comment]
Question @clalancette :

The tutorial mentions license:
```
<license>Apache License 2.0</license>
```

The license identifier generated by `ros2 pkg create` is the spdx version : 
```
<license>Apache-2.0</license>
```

Which format should be used ? Is there a prefered one ?

**Comment by clalancette** [comment]
> Which format should be used ? Is there a prefered one ?

We slightly prefer the SPDX identifier (Apache-2.0), though we are not consistent about this, even in the core.

**Comment by clalancette** [comment]
I'm going to go ahead and close this, as the question about the license is somewhat larger (which is hinted at by https://github.com/ros-infrastructure/rep/pull/347 as well).  Thanks for testing!

**Comment by mikaelarguedas** [comment]
Alright thanks,

PR for license mismatch in tutorials here https://github.com/ros2/ros2_documentation/pull/4395
