### ISSUE TITLE
Adding Physical and Collision Properties to a URDF Model

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1180]
Check the documentation for the 'Adding Physical and Collision Properties to a URDF Model' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Adding Physical and Collision Properties to a URDF Model page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/URDF/Adding-Physical-and-Collision-Properties-to-a-URDF-Model.html)

**Comment by jasmeet0915** [comment]
Hi, could you assign this issue to me?
