### ISSUE TITLE
Building a Visual Robot Model with URDF from Scratch

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1182]
Check the documentation for the 'Building a Visual Robot Model with URDF from Scratch' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [Building a Visual Robot Model with URDF from Scratch page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/URDF/Building-a-Visual-Robot-Model-with-URDF-from-Scratch.html)

**Comment by jasmeet0915** [comment]
Hi, I have followed all the steps in the tutorial and was able to correctly visualize the urdf in RViz2:

![Screenshot from 2024-05-08 02-12-21](https://github.com/osrf/ros2_test_cases/assets/23265149/7e941b40-25b8-4550-8292-1aa759c0e746)

**Comment by clalancette** [comment]
Great, thank you for testing!
