### ISSUE TITLE
URDF Main

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1184]
Check the documentation for the 'URDF Main' page

## Configuration

* Chip set: AMD64
* Build type: Debian
* OS: Ubuntu Noble 24.04
* DDS: FastDDS

## Links

* [URDF Main page](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/URDF/URDF-Main.html)

**Comment by jasmeet0915** [comment]
This is an index page. I tested all the links and they work correctly!
