### ISSUE TITLE
ROS 1 bridge

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1216]
## Configuration

* DDS: FastDDS
* Build type: Debian
* OS: Ubuntu Noble 24.04
* Chip set: AMD64

## Links

* [Reference URL](https://github.com/ros2/ros1_bridge)

### Step 1 - Build ros1_bridge
            
        

    
    

    
        
        
Follow the instructions in the README to compile the bridge
                
    

    
    
            
### Step 2 - Run the birdge with talker and listener
            
        

    
    

    
        
        
Follow the instructions in the readme to run Example 1.
                
    

    
    
            
### Step 3 - Run the birdge and exchange images
            
        

    
    

    
        
        
Follow the instructions in the readme to run Example 2.
                
    

    
    
            
### Step 4 - Run the birdge and AddTwoInts service
            
        

    
    

    
        
        
Follow the instructions in the readme to run Example 3.
                
    

    
    
            
### Step 5 - Run the bridge with only selected topics and services.
            
        

    
    

    
        
        
Follow the instructions in the readme to run Example 4.

**Comment by clalancette** [comment]
Closing as we don't support the bridge in Ubuntu 24.04.
