### ISSUE TITLE
Executables in `pendulum_control`

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1265]
## Configuration

* OS: Ubuntu Noble 24.04
* Chip set: AMD64
* Build type: Debian
* DDS: CycloneDDS

### Step 1 - Check `pendulum_demo`
            
        

    
    

    
        
        
```bash
# StdIn - terminal 1
ros2 run pendulum_control pendulum_demo
```
                
    

    
    
            
### Step 2 - Check `pendulum_teleop`
            
        

    
    

    
        
        
```bash
# StdIn - terminal 1
ros2 run pendulum_control pendulum_teleop
```
                
    

    
    
            
### Step 3 - Check `pendulum_launch.bash`
            
        

    
    

    
        
        
```bash
# StdIn - terminal 1
ros2 launch pendulum_control pendulum_launch.bash
```
                
    

    
    
            
### Step 4 - Check `pendulum_logger`
            
        

    
    

    
        
        
```bash
# StdIn - terminal 1
ros2 run pendulum_control pendulum_logger
```

**Comment by mikaelarguedas** [comment]
:heavy_check_mark: All tests passed


All good except non-existing executable adressed in https://github.com/osrf/ros2_test_cases/pull/1546
