### ISSUE TITLE
Executables in `rttest`

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1268]
## Configuration

* DDS: FastDDS
* Build type: Debian
* OS: Ubuntu Noble 24.04
* Chip set: AMD64

### Run pendulum_demo to generate data

```bash
# StdIn - terminal 1
ros2 run pendulum_control pendulum_demo -f pendulum_demo_results
```
    
            
### Check `rttest_plot`
            
        

    
    

    
        
        
```bash
# StdIn - terminal 1
ros2 run rttest rttest_plot -s pendulum_demo_results
```

**Comment by Kartik9250** [comment]
I would like to work on this

**Comment by Kartik9250** [comment]
The `ros2 run rttest rttest_plot` give out the output given below:
```usage: rttest_plot [-h] [-s] [-o OUTFILE] filename
rttest_plot: error: the following arguments are required: filename
[ros2run]: Process exited with failure 2
```
What file am I supposed to provide it.

**Comment by clalancette** [comment]
> What file am I supposed to provide it.

Hm, good question.  I'll take a look and see if I can figure it out.

**Comment by clalancette** [comment]
All right, I figured it out.  I opened up https://github.com/osrf/ros2_test_cases/pull/1553 to update the test case, and I manually modified this test case to show the proper instructions.  @Kartik9250 you should be able to follow and test this one now.

**Comment by clalancette** [comment]
Since I think this one is solved, I'm going to go ahead and close it.  Thanks for testing!
