### ISSUE TITLE
Executables in `rttest`

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1269]
## Configuration

* OS: Ubuntu Noble 24.04
* Chip set: AMD64
* Build type: Debian
* DDS: CycloneDDS

### Check `rttest_plot`
            
        

    
    

    
        
        
```bash
# StdIn - terminal 1
ros2 run rttest rttest_plot
```

**Comment by jasmeet0915** [comment]
Could you assign this issue to me?

**Comment by jasmeet0915** [comment]
I have tested this issue using results from the pendulum_demo and plots are generated as expected:

![Screenshot from 2024-05-08 00-17-45](https://github.com/osrf/ros2_test_cases/assets/23265149/6d5ad124-a09f-4d1d-87f5-6468365299cc)

**Comment by clalancette** [comment]
Great, thanks for testing!
