### ISSUE TITLE
Executables in gz vendor packages

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1274]
You will need to install the `desktop-full` or `simulation` variants before running this test.

## Configuration

* DDS: FastDDS
* Build type: Debian
* OS: Ubuntu Noble 24.04
* Chip set: AMD64

### Check `gz sim -v4 shapes.sdf`
            
        

    
    

    
        
        
```bash
# StdIn - terminal 1
gz sim -v4 shapes.sdf
```

**Comment by Ayush1285** [comment]
This works fine as expected.
![Screenshot from 2024-05-03 02-11-36](https://github.com/osrf/ros2_test_cases/assets/64409716/d8619af6-c288-4b6d-9aa9-426d7ce58342)

But if we go to the tutorial([link](https://docs.ros.org/en/jazzy/Tutorials/Advanced/Simulators/Gazebo/Gazebo.html)) provided in Documentation of Jazzy. It still mentions the "ign gazebo ..." command. It is not supported in Gazebo Harmonic(default pairing with Jazzy).

**Comment by clalancette** [comment]
> It is not supported in Gazebo Harmonic(default pairing with Jazzy). "ign gazebo" is supported in Gazebo Fortress I think.

Yeah, good point.  We are just waiting for https://github.com/ros2/ros2_documentation/pull/4311 to be finished and land, and then that will be fixed.  I'll leave this open until then.

**Comment by clalancette** [comment]
We are close to landing that PR, so closing this out for now.  Thanks for testing!
