### ISSUE TITLE
Executables in gz vendor packages

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1275]
You will need to install the `desktop-full` or `simulation` variants before running this test.

## Configuration

* OS: Ubuntu Noble 24.04
* Chip set: AMD64
* Build type: Debian
* DDS: CycloneDDS

### Check `gz sim -v4 shapes.sdf`
            
        

    
    

    
        
        
```bash
# StdIn - terminal 1
gz sim -v4 shapes.sdf
```

**Comment by jasmeet0915** [comment]
Could you assign this issue to me?

**Comment by clalancette** [comment]
Thanks for testing!
