### ISSUE TITLE
Check ROS 2 security CLI on Linux

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1306]
## Configuration

* DDS: FastDDS
* Build type: Debian
* OS: Ubuntu Noble 24.04
* Chip set: AMD64

## Links

* [Tutorial URL](https://github.com/ros2/sros2/blob/master/SROS2_Linux.md)

**Comment by fujitatomoya** [comment]
@marcoag you can sign me up on this.

**Comment by fujitatomoya** [comment]
> Note: Fast-RTPS requires an additional CMake flag to build the security plugins so the colcon invocation needs to be modified to pass:

https://github.com/ros2/sros2/blob/master/SROS2_Linux.md tells that we need to rebuild the Fast-DDS, but this is not actually necessary.

I had the following result without rebuilding Fast-DDS.

- talker terminal

```bash
root@51cdd59e1f3e:~/sros2_demo# ros2 security create_keystore demo_keystore
root@51cdd59e1f3e:~/sros2_demo# ros2 security create_enclave demo_keystore /talker_listener/talker
root@51cdd59e1f3e:~/sros2_demo# ros2 security create_enclave demo_keystore /talker_listener/listener
root@51cdd59e1f3e:~/sros2_demo# export ROS_SECURITY_KEYSTORE=~/sros2_demo/demo_keystore
root@51cdd59e1f3e:~/sros2_demo# export ROS_SECURITY_ENABLE=true
root@51cdd59e1f3e:~/sros2_demo# export ROS_SECURITY_STRATEGY=Enforce
root@51cdd59e1f3e:~/sros2_demo# export ROS_SECURITY_KEYSTORE=~/sros2_demo/demo_keystore
root@51cdd59e1f3e:~/sros2_demo# export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
root@51cdd59e1f3e:~/sros2_demo# ros2 run demo_nodes_cpp talker --ros-args --enclave /talker_listener/talker
[INFO] [1714623024.540831933] [rcl]: Found security directory: /root/sros2_demo/demo_keystore/enclaves/talker_listener/talker
[INFO] [1714623025.552864377] [talker]: Publishing: 'Hello World: 1'
[INFO] [1714623026.552860641] [talker]: Publishing: 'Hello World: 2'
[INFO] [1714623027.552883386] [talker]: Publishing: 'Hello World: 3'
[INFO] [1714623028.552875916] [talker]: Publishing: 'Hello World: 4'
[INFO] [1714623029.552856397] [talker]: Publishing: 'Hello World: 5'
[INFO] [1714623030.552879266] [talker]: Publishing: 'Hello World: 6'
[INFO] [1714623031.552951655] [talker]: Publishing: 'Hello World: 7'
[INFO] [1714623032.552886215] [talker]: Publishing: 'Hello World: 8'
...
```

- listener terminal

```bash
root@51cdd59e1f3e:~/sros2_demo# export ROS_SECURITY_KEYSTORE=~/sros2_demo/demo_keystore
root@51cdd59e1f3e:~/sros2_demo# export ROS_SECURITY_STRATEGY=Enforce
root@51cdd59e1f3e:~/sros2_demo# export ROS_SECURITY_ENABLE=true
root@51cdd59e1f3e:~/sros2_demo# export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
root@51cdd59e1f3e:~/sros2_demo# ros2 run demo_nodes_py listener --ros-args --enclave /talker_listener/listener
[INFO] [1714623026.373588788] [rcl]: Found security directory: /root/sros2_demo/demo_keystore/enclaves/talker_listener/listener
[INFO] [1714623028.565438387] [listener]: I heard: [Hello World: 4]
[INFO] [1714623029.555288925] [listener]: I heard: [Hello World: 5]
[INFO] [1714623030.555303750] [listener]: I heard: [Hello World: 6]
[INFO] [1714623031.556143568] [listener]: I heard: [Hello World: 7]
[INFO] [1714623032.555317107] [listener]: I heard: [Hello World: 8]
...
```

**Comment by wjwwood** [comment]
Do you think we should change the docs or is this good to close? I don't personally know if this step is only sometimes needed or if it's just old info.

**Comment by fujitatomoya** [comment]
@wjwwood i will check the build option for Fast-DDS to make sure this doc is no more needed. and i will come up with PR if need. i can take care of this.

**Comment by fujitatomoya** [comment]
@wjwwood @marcoag i think we can close this because the procedure that is what need to verify here works without problems.

i created the issue to track rmw_fastrtps security build option here, https://github.com/ros2/sros2/issues/294. i will take care of this.

**Comment by fujitatomoya** [comment]
> i created the issue to track rmw_fastrtps security build option here, https://github.com/ros2/sros2/issues/294. i will take care of this.

see https://github.com/ros2/sros2/issues/294#issuecomment-2090959423 (@clalancette thanks!)

after all, no problem observed on this issue. we can close this.

**Comment by clalancette** [comment]
Sounds good, thanks for testing!

**Comment by mikaelarguedas** [comment]
FYI: I tested this and the behavior were the same as https://github.com/osrf/ros2_test_cases/issues/1307#issuecomment-2094470885 -> the authentication/encryption worked, the access control part was broken

After applying https://github.com/ros2/sros2/pull/295 the entire tutorial works as expected :+1:
