### ISSUE TITLE
Check ROS 2 security CLI on Linux

### ISSUE THREAD

**Issue by marcoag** [osrf/ros2_test_cases#1307]
## Configuration

* OS: Ubuntu Noble 24.04
* Chip set: AMD64
* Build type: Debian
* DDS: CycloneDDS

## Links

* [Tutorial URL](https://github.com/ros2/sros2/blob/master/SROS2_Linux.md)

**Comment by mikaelarguedas** [comment]
- Talker / listener using encryption: :heavy_check_mark:
- Access control: :x: 
    Fixed by https://github.com/ros2/sros2/pull/295
- Run the demo on different machines: not tested
- Certificate Revocation Lists :heavy_check_mark:

**Comment by mikaelarguedas** [comment]
PR fixing the issue has been merged so I believe this is good to close :+1:
