### ISSUE TITLE
Test cross-vendor DDS pub/sub compatibility

### ISSUE THREAD

**Issue by Ryanf55** [osrf/ros2_test_cases#1543]
OS: Ubuntu 24
Arch: AMD64
ROS Version: Jazzy
Build Type: Binary 

Test:
1. Install fastdds
1. Install cyclonedds
1. Create a string "hello world" publisher in CLI
1. Create a string "hello world" subscriber in CLI with a different DDS vendor
1. Verify  the pub/sub works
1. Swap the publisher and subscriber

**Comment by mikaelarguedas** [comment]
I tested this while testing the minimal examples executable for all topice pub / sub and service server / client configurations

(between fastdds and cyclonedds, I didnt test with connext)
