### ISSUE TITLE
ros2 run turtlesim turtlesim_node runing with xrdp

### ISSUE THREAD

**Issue by clemefr** [osrf/ros2_test_cases#1548]
[INFO] [1714754369.661115968] [turtlesim]: Starting turtlesim with node name /turtlesim
[INFO] [1714754369.666778611] [turtlesim]: Spawning turtle [turtle1] at x=[5.544445], y=[5.544445], theta=[0.000000]
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen

It is working but with these error that I do not know are relevant!!!
I even do not know if it is right to run in xrdp...

**Comment by clalancette** [comment]
> It is working but with these error that I do not know are relevant!!!
> I even do not know if it is right to run in xrdp...

Yeah, we are seeing that everywhere.  It seems to be a new error with MESA and glx.  It doesn't seem to be harming anything, so I think we can say that it is successful.

Thanks for testing!
