### ISSUE TITLE
The requested URL /en/jazzy/p/launch/architecture.html was not found on this server.

### ISSUE THREAD

**Issue by clemefr** [osrf/ros2_test_cases#1550]
Not Found
The requested URL /en/jazzy/p/launch/architecture.html was not found on this server.

from the link 
[Documentation](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Launch/Launch-system.html#id8)[](https://docs.ros.org/en/jazzy/Tutorials/Intermediate/Launch/Launch-system.html#documentation)
[The launch documentation](https://docs.ros.org/en/jazzy/p/launch/architecture.html) provides more details on concepts that are also used in launch_ros.
in Launch tutorial

**Comment by clalancette** [comment]
Good call.  We forgot a setup step there, so we were not updating the documentation.  That has now been fixed and the documentation is available.  Thanks for testing!
