### ISSUE TITLE
Ament CMake Documentation

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#940]
Check the documentation for the 'Ament CMake Documentation' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Ament CMake Documentation page](https://docs.ros.org/en/iron/Tutorials/Ament-CMake-Documentation.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by karmenlu** [comment]
Was able to follow. No obvious errors.

**Comment by Yadunund** [comment]
Awesome, thanks for testing!
