### ISSUE TITLE
Composition

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#948]
Check the documentation for the 'Composition' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Composition page](https://docs.ros.org/en/iron/Tutorials/Intermediate/Composition.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by BorisBoutillier** [comment]
In a debian jammy installation with fastDDS.

I have followed the documentation page for "Composing multiple nodes in a single process"

I was able to follow the documentation and run the different code sections. The documentation was clear to me, and I have not seen any obvious errors.

I would just propose a slight improvment ( not-compulsory at all) to make all "Run the demos" sections coherent, it is to add a link to the composition_demo_launch.py source code in the "Composition using launch actions" section, with something like:  [source code](https://github.com/ros2/demos/blob/iron/composition/launch/composition_demo_launch.py)
All other "Run the demos" have pointer to the source code, which I feel useful.


Screenshots of my session:
![Test4](https://user-images.githubusercontent.com/18518188/236791694-3526e1be-d3c7-4476-809e-757030b4f473.png)
![Test3](https://user-images.githubusercontent.com/18518188/236791700-47ef4628-fd69-43cd-a206-ab641a7f8de7.png)
![Test2](https://user-images.githubusercontent.com/18518188/236791703-d879d30c-fb66-4a7c-93f5-946c116c2565.png)
![Test1](https://user-images.githubusercontent.com/18518188/236791707-d8bee2e5-f5d6-4e88-bf8d-e60fc295055c.png)

**Comment by clalancette** [comment]
> I would just propose a slight improvment ( not-compulsory at all) to make all "Run the demos" sections coherent, it is to add a link to the composition_demo_launch.py source code in the "Composition using launch actions" section, with something like: [source code](https://github.com/ros2/demos/blob/iron/composition/launch/composition_demo_launch.py)

Good catch!  I agree that is useful.  I've opened up https://github.com/ros2/ros2_documentation/pull/3553 to add this in.

With that said, the rest of this looks good, so I'll close this out.  Thank you for testing!
