### ISSUE TITLE
Deploying ROS 2 on IBM Cloud

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#960]
Check the documentation for the 'Deploying ROS 2 on IBM Cloud' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Deploying ROS 2 on IBM Cloud page](https://docs.ros.org/en/iron/Tutorials/Miscellaneous/Deploying-ROS-2-on-IBM-Cloud.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by pradyum** [comment]
Hi, there is no iron docker image released yet. Should I this documentation test with foxy, rolling or humble image?

**Comment by Yadunund** [comment]
Please use rolling!

**Comment by clalancette** [comment]
This one didn't get testing, but I think we are going to skip it next year anyway so closing this out.
