### ISSUE TITLE
FastDDS Configuration

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#966]
Check the documentation for the 'FastDDS Configuration' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [FastDDS Configuration page](https://docs.ros.org/en/iron/Tutorials/FastDDS-Configuration/FastDDS-Configuration.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by iuhilnehc-ynos** [comment]
* [x]  **I was able to follow the documentation.**
* [x]  **The documentation seemed clear to me.**
* [x]  **The documentation didn't have any obvious errors.**

Found a log missing a period in the doc.
```
[INFO] [1612977403.805799037] [ping_server]: Ready to serve
```

<details><summary> log </summary>
<p>

- Limiting the number of matching subscribers

![Screenshot from 2023-05-15 09-38-15](https://github.com/osrf/ros2_test_cases/assets/64191023/423b49c7-1e85-458e-8531-c0ae4e64c08c)

- Using partitions within the topic

![Screenshot from 2023-05-15 09-44-09](https://github.com/osrf/ros2_test_cases/assets/64191023/950babaa-ba3a-44e8-81cc-b88a518d2c07)

- Configuring a service and a client

![Screenshot from 2023-05-15 09-50-13](https://github.com/osrf/ros2_test_cases/assets/64191023/6b5c1fc0-b701-4728-9520-e32c9c0c0908)

</p>
</details>

**Comment by Yadunund** [comment]
Awesome, thanks for testing!
