### ISSUE TITLE
Gazebo

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#967]
Check the documentation for the 'Gazebo' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Gazebo page](https://docs.ros.org/en/iron/Tutorials/Advanced/Simulators/Gazebo.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by klu17** [comment]
Was able tutorial up to '2 Configuring ROS 2'. At the point, I got an error: `Package 'ros_gz_bridge' not found` and was not able to find `ros_gz_bridge` install instructions for iron at [ROS Index]( https://index.ros.org/p/ros_gz_bridge/).

![Gazebo launched](https://github.com/osrf/ros2_test_cases/assets/20442297/63bf57fe-58e0-44ab-84b8-726f078cb772)
![ign topics](https://github.com/osrf/ros2_test_cases/assets/20442297/8fa3b813-82ee-4876-85bb-b12d7d3867f5)
![No iron on ros_gz_bridge ROS index](https://github.com/osrf/ros2_test_cases/assets/20442297/260f136a-33da-4f37-9bc2-fe347e0160cf)

**Comment by Yadunund** [comment]
Thanks for trying this. Turns out we're still in the process of releasing debians for [ros_gz](https://github.com/gazebosim/ros_gz) which is why you're unable to install it at the moment. Will update once that's ready.

**Comment by clalancette** [comment]
These packages weren't available, but should be available now.  With the tutorial party over, I'm going to close this out.  Thanks for your efforts here.
