### ISSUE TITLE
Ignition

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#969]
Check the documentation for the 'Ignition' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Ignition page](https://docs.ros.org/en/iron/Tutorials/Advanced/Simulators/Ignition.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by karmenlu** [comment]
Unable to complete steps after [2 Configuring ROS2](https://docs.ros.org/en/iron/Tutorials/Advanced/Simulators/Gazebo.html#configuring-ros-2). Similar to another issue I tested, installing ros_gz_bridge is a blocking step.

![image](https://github.com/osrf/ros2_test_cases/assets/20442297/a188aed2-0eb1-49c0-a7c7-e6e0667efcd4)

**Comment by Yadunund** [comment]
This ticket should not have been created as it's a duplicate of https://docs.ros.org/en/iron/Tutorials/Advanced/Simulators/Gazebo.html. It probably got created due to a redirect link in the website. Will close this one and follow up in the other.
