### ISSUE TITLE
Intermediate

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#970]
Check the documentation for the 'Intermediate' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Intermediate page](https://docs.ros.org/en/iron/Tutorials/Intermediate.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by christophebedard** [comment]
@Bi0T1N you mentioned this issue in https://github.com/ros2/ros2_documentation/pull/3526, but I'm not sure if that is really related to this issue. Is it related?

**Comment by christophebedard** [comment]
Otherwise, there isn't much to validate here; the list of tutorials looks good and matches the sidebar.

**Comment by clalancette** [comment]
Thanks for testing!  I'm going to close this out because I agree that it isn't much related to the `ros2_documentation` PR.

**Comment by Bi0T1N** [comment]
> @Bi0T1N you mentioned this issue in [ros2/ros2_documentation#3526](https://github.com/ros2/ros2_documentation/pull/3526), but I'm not sure if that is really related to this issue. Is it related?

Its partly related but the path was fixed already. Other changes are additional...
