### ISSUE TITLE
Introducing ros2 security

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#972]
Check the documentation for the 'Introducing ros2 security' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Introducing ros2 security page](https://docs.ros.org/en/iron/Tutorials/Advanced/Security/Introducing-ros2-security.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by klu17** [comment]
I'll take this one. I was able to follow through the tutorial and receive messages on the listener:

![image](https://github.com/osrf/ros2_test_cases/assets/20442297/dc83a49f-5f91-47e7-8275-ccca3f9ebdc7)

**Comment by clalancette** [comment]
Thank you for testing!
