### ISSUE TITLE
Launch files migration guide

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#976]
Check the documentation for the 'Launch files migration guide' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Launch files migration guide page](https://docs.ros.org/en/iron/Tutorials/Launch-files-migration-guide.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by SrijaneeBiswas** [comment]
Assigned to myself.

Can successfully confirm the following:
[x]: I was able to follow the documentation.
[x]: The documentation seemed clear to me.
[x]: The documentation didn't have any obvious errors.

**Comment by Yadunund** [comment]
Thanks for testing!
