### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#988]
Check the documentation for the 'Python' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Python page](https://docs.ros.org/en/iron/Tutorials/Intermediate/Testing/Python.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by BorisBoutillier** [comment]
On a debian jammy installation with fastdds.

I have followed the Test tutorials, including the "Writing Basic Tests with Python" for this test case.

I have been able to follow the documentation, it seemed clear to me. I did not see any error in the wording or links.


![Screenshot from 2023-05-08 11-53-44](https://user-images.githubusercontent.com/18518188/236794600-ece0c9f0-86be-453f-927e-3273983e0cdc.png)
