### ISSUE TITLE
Rosdep

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#996]
Check the documentation for the 'Rosdep' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [Rosdep page](https://docs.ros.org/en/iron/Tutorials/Intermediate/Rosdep.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by BorisBoutillier** [comment]
On a debian jammy installation with fastDDS.

I have read through the Rosdep documentation page.

I was able to follow the documentation, it seemed clear to me. I did not see any obvious errors in working, code section or http links.
