### ISSUE TITLE
RQt Overview Usage

### ISSUE THREAD

**Issue by Yadunund** [osrf/ros2_test_cases#997]
Check the documentation for the 'RQt Overview Usage' page

## Setup
- DDS vendor: FastDDS
- BuildType: Debian
- Os: Ubuntu Jammy
- Chip: Amd64

## Links
- [RQt Overview Usage page](https://docs.ros.org/en/iron/Tutorials/RQt-Overview-Usage.html)

## Checks
- [ ] **I was able to follow the documentation.**
- [ ] **The documentation seemed clear to me.**
- [ ] **The documentation didn't have any obvious errors.**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by karmenlu** [comment]
:heavy_check_mark: Able to follow all steps in RQt Overview Usage page. 

![image](https://github.com/osrf/ros2_test_cases/assets/20442297/5a640273-026c-494d-ad1f-f2b46b4d8880)

![image](https://github.com/osrf/ros2_test_cases/assets/20442297/b397eacb-1580-41b8-bcbc-076d06e2855c)

**Comment by clalancette** [comment]
Thanks for testing!
